# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload app to testflight"
  lane :beta do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120" 
    setup_ci
    match(
      type: "appstore", 
      app_identifier:ENV["BUNDLE_IDENTIFIER"],
      readonly: true
    )
    app_store_connect_api_key(
      key_id:ENV["APPSTORE_CONNECT_KEY_ID"],
      issuer_id:ENV["APPSTORE_CONNECT_ISSUER_ID"],
      key_content:ENV["APPSTORE_CONNECT_KEY_CONTENT"]
    )
    build_app(project:"Siksha.xcodeproj",scheme:"Siksha-Release",clean:true, silent:true)
    increment_build_number(build_number:ENV["BUILD_NUMBER"],xcodeproj:"Siksha.xcodeproj")
    increment_version_number(version_number:ENV["VERSION_NUMBER"],xcodeproj:"Siksha.xcodeproj")
    upload_to_testflight(app_version:ENV["VERSION_NUMBER"])
    slack(message:"uploaded to testflight")
    # add actions here: https://docs.fastlane.tools/actions
  end

end

lane :register_new_devices do
  register_devices(
    devices_file: "./devices.txt"
  )
end
